Update 0-iamsomeonelese

diff --git a/0x12-web_stack_debugging_2/0-iamsomeonelese b/0x12-web_stack_debugging_2/0-iamsomeonelese
--- a/0x12-web_stack_debugging_2/0-iamsomeonelese
+++ b/0x12-web_stack_debugging_2/0-iamsomeonelese
@@ -1,3 +1,17 @@
 #!/usr/bin/env bash
-# runs the whomai command under the user passed as an argument
-sudo -u "$1" whoami
+
+if [ $# -ne 1 ]; then
+  echo "Usage: $0 <username>"
+  exit 1
+fi
+
+username="$1"
+
+# Check if the user exists
+if ! id "$username" &>/dev/null; then
+  echo "Error: User '$username' does not exist."
+  exit 1
+fi
+
+# Run whoami command under the specified user
+sudo -u "$username" whoami
